language: generic  # might not be needed. could fail travis builds
sudo: required
services:
  - docker

before_install:
  - docker build -t davidatthepark/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true davidatthepark/react-test npm test -- --coverage

after_success:
  - docker build -t davidatthepark/multi-container-client ./client
  - docker build -t davidatthepark/multi-container-nginx ./nginx
  - docker build -t davidatthepark/multi-container-server ./server
  - docker build -t davidatthepark/multi-container-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push davidatthepark/multi-container-client
  - docker push davidatthepark/multi-container-nginx
  - docker push davidatthepark/multi-container-server
  - docker push davidatthepark/multi-container-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: test
  env: Test-env
  bucket_name: elasticbeanstalk-us-west-1-511995543734
  bucket_path: test
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
